// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVbJznAzC5Xc9ipXQZcVziPk32X_Nx248',
    appId: '1:821916941556:web:8ef7888455c556bfe7f2a1',
    messagingSenderId: '821916941556',
    projectId: 'encuesta-5cbfa',
    authDomain: 'encuesta-5cbfa.firebaseapp.com',
    storageBucket: 'encuesta-5cbfa.appspot.com',
    measurementId: 'G-PZTZGPR88N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkqIhszyQF3NncoLD07trry94Cp-jc2ZQ',
    appId: '1:821916941556:android:d31eefa06a913ebee7f2a1',
    messagingSenderId: '821916941556',
    projectId: 'encuesta-5cbfa',
    storageBucket: 'encuesta-5cbfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtO_hT4xzlnU61S7oli58ZSHC1m8FkqM',
    appId: '1:821916941556:ios:4acb1bf86b0fb6c8e7f2a1',
    messagingSenderId: '821916941556',
    projectId: 'encuesta-5cbfa',
    storageBucket: 'encuesta-5cbfa.appspot.com',
    iosBundleId: 'com.easd.code.encuesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtO_hT4xzlnU61S7oli58ZSHC1m8FkqM',
    appId: '1:821916941556:ios:c0061416c4380822e7f2a1',
    messagingSenderId: '821916941556',
    projectId: 'encuesta-5cbfa',
    storageBucket: 'encuesta-5cbfa.appspot.com',
    iosBundleId: 'com.easd.code.encuesta.RunnerTests',
  );
}
